import React from 'react';
import {
  SafeAreaView,
  StatusBar,
  View,
  Platform,
  UIManager,
  YellowBox
} from 'react-native';
import styled from 'styled-components';
import { BleManager } from 'react-native-ble-plx';
import MainContainer from '../components/home/content/MainContainer/MainContainer';

// autogenerated - is it required?
declare var global: { HermesInternal: null | {} };

if (Platform.OS === 'android') {
  if (UIManager.setLayoutAnimationEnabledExperimental) {
    UIManager.setLayoutAnimationEnabledExperimental(true);
  }
}

//

YellowBox.ignoreWarnings(['Animated: `useNativeDriver` was not specified.']); // color-picker

// should we move it as property to App and pass it with Context?
export const bleManager = new BleManager();

const App = () => {
  return (
    <Container>
      <StatusBar barStyle="light-content" />
      <SafeAreaView>
        <MainContainer />
      </SafeAreaView>
    </Container>
  );
};

const Container = styled(View)`
  width: 100%;
  height: 100%;
  background-color: black;
`;

export default App;
